defaultAccount: "developer-test"
accounts:
  - name: "developer-test"
    accountId: 149041124
    portalId: 149041124
    env: eu1
    authType: personalaccesskey
    accountType: STANDARD
    personalAccessKey: "pat-eu1-149041124-fake-key-for-ci-project-validation"
    auth:
      tokenInfo:
        accessToken: "pat-eu1-149041124-fake-key-for-ci-project-validation"
        expiresAt: "2099-01-01T00:00:00.000Z"
