version: "1.0.0"
installations:
  "149041124":
    executionPortalId: 149041124
    accountRole: "developer-test"
    organizationKey: "org_global_corp"
    allowedRelationshipTypes:
      - "b2b"
      - "b2c"
    defaultRelationshipType: "b2b"
    expectedConfigVersion: "1.0.0"
