import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'yaml';

function compileConfigs() {
  const rootDir = path.join(__dirname, '../');
  const configDir = path.join(rootDir, 'config/organizations');
  const installationsPath = path.join(rootDir, 'config/portal-installations.yaml');
  const outputPath = path.join(rootDir, 'packages/domain/embedded-configs.ts');

  // Load installations
  let installations: Record<string, any> = {};
  if (fs.existsSync(installationsPath)) {
    const raw = fs.readFileSync(installationsPath, 'utf-8');
    const parsed = yaml.parse(raw);
    installations = parsed?.installations || {};
  }

  // Load organization configs
  const configs: Record<string, any> = {};
  if (fs.existsSync(configDir)) {
    const files = fs.readdirSync(configDir).filter(f => f.endsWith('.yaml') || f.endsWith('.yml'));
    for (const file of files) {
      const raw = fs.readFileSync(path.join(configDir, file), 'utf-8');
      const parsed = yaml.parse(raw);
      if (parsed && parsed.organizationKey && parsed.relationshipType) {
        const key = `${parsed.organizationKey}:${parsed.relationshipType}`;
        configs[key] = parsed;
      }
    }
  }

  const code = `// AUTO-GENERATED BY scripts/compile-configs.ts - DO NOT EDIT MANUALLY
export const EMBEDDED_INSTALLATIONS: Record<string, { organizationKey: string; defaultRelationshipType: string }> = ${JSON.stringify(installations, null, 2)};

export const EMBEDDED_CONFIGS: Record<string, any> = ${JSON.stringify(configs, null, 2)};
`;

  fs.writeFileSync(outputPath, code, 'utf-8');
  console.log('Successfully generated packages/domain/embedded-configs.ts', {
    installations: Object.keys(installations),
    configs: Object.keys(configs)
  });
}

if (require.main === module) {
  compileConfigs();
}
