// AUTO-GENERATED BY scripts/compile-configs.ts - DO NOT EDIT MANUALLY
export const EMBEDDED_INSTALLATIONS: Record<string, { executionPortalId?: number; accountRole?: string; organizationKey: string; allowedRelationshipTypes?: string[]; defaultRelationshipType?: string; expectedConfigVersion?: string }> = {
  "149041124": {
    "executionPortalId": 149041124,
    "accountRole": "developer-test",
    "organizationKey": "org_global_corp",
    "allowedRelationshipTypes": [
      "b2b",
      "b2c"
    ],
    "defaultRelationshipType": "b2b",
    "expectedConfigVersion": "1.0.0"
  }
};

export const EMBEDDED_CONFIGS: Record<string, any> = {
  "org_global_corp:b2b": {
    "organizationKey": "org_global_corp",
    "configVersion": "1.0.0",
    "relationshipType": "b2b",
    "hubspotPipelines": {
      "leadPipelineId": "b2b_qualification_lead_pipeline",
      "dealPipelineId": "b2b_transaction_deal_pipeline",
      "dealStageProbabilities": {
        "open": 0.2,
        "closedwon": 1,
        "closedlost": 0
      }
    },
    "offeringPolicy": {
      "productOfferingKeyProperty": "hs_sku",
      "rtpPolicy": "carryForward"
    },
    "goalsByOpportunityType": {
      "MQL": [
        {
          "key": "b2b_marketing_consent",
          "name": "Explicit marketing consent",
          "predicate": "property",
          "scope": "relationship",
          "params": {
            "property": "marketingConsent",
            "equals": true
          }
        }
      ],
      "SQL": [
        {
          "key": "b2b_positive_meeting",
          "name": "Completed positive meeting outcome",
          "predicate": "activityExists",
          "scope": "opportunity",
          "params": {
            "activityType": "MEETING",
            "outcome": "COMPLETED"
          }
        }
      ],
      "FTP": [
        {
          "key": "b2b_deal_closed_won",
          "name": "First B2B transaction deal closed won",
          "predicate": "transactionExists",
          "scope": "opportunity"
        }
      ],
      "RTP": [
        {
          "key": "b2b_deal_closed_won_repeat",
          "name": "Subsequent B2B transaction deal closed won",
          "predicate": "transactionExists",
          "scope": "sincePredecessorCompletion"
        }
      ]
    },
    "featureFlags": {
      "automationSuppressed": false,
      "dryRunTransactions": false
    }
  },
  "org_global_corp:b2c": {
    "organizationKey": "org_global_corp",
    "configVersion": "1.0.0",
    "relationshipType": "b2c",
    "hubspotPipelines": {
      "leadPipelineId": "b2c_qualification_lead_pipeline",
      "dealPipelineId": "b2c_transaction_deal_pipeline",
      "dealStageProbabilities": {
        "open": 0.5,
        "closedwon": 1,
        "closedlost": 0
      }
    },
    "offeringPolicy": {
      "productOfferingKeyProperty": "hs_sku",
      "rtpPolicy": "emptyUntilKnown"
    },
    "goalsByOpportunityType": {
      "MQL": [],
      "SQL": [
        {
          "key": "b2c_cart_interest",
          "name": "B2C cart interest or offering proposition",
          "predicate": "offeringKnown",
          "scope": "opportunity"
        }
      ],
      "FTP": [
        {
          "key": "b2c_deal_closed_won",
          "name": "First B2C transaction deal closed won",
          "predicate": "transactionExists",
          "scope": "opportunity"
        }
      ],
      "RTP": [
        {
          "key": "b2c_deal_closed_won_repeat",
          "name": "Repeat B2C transaction deal closed won",
          "predicate": "transactionExists",
          "scope": "sincePredecessorCompletion"
        }
      ]
    },
    "featureFlags": {
      "automationSuppressed": false,
      "dryRunTransactions": true
    }
  }
};
